### ISSUE TITLE
Data point alignment

### ISSUE THREAD

**Issue by bionicfish** [datavisyn/chartjs-chart-box-and-violin-plot#10]
When specific data points are plotted on the box chart they appear randomly across the width of the box chart area, opposed to horizontally centered to the box cart? Is there a way of forcing the individual data point plots to center? 

The first sample chart on the readme page show this, the pink box chart has all the points aligned, while the blue are scatter? How do I get the points to align like the pink box chart?

Update: After looking at the boxplots vs boxplotsArray function in the util.js, the pink/red chart is only showing the outliers which are centered, but the other chart (blue) is showing all the data points which seem to be scattered (eg similar to the violin plot?), how do I either center them? or hide them?

**Comment by sgratzl** [comment]
you are right, the outliers are centered while the raw datapoints are jittered. The idea was that since the individual data points are a lot aligning them on a single axis will lead to heavy overplotting. jittering the data points is therefore a common strategy.

**Comment by sgratzl** [comment]
the jittering cannot be disabled atm. However to disable rendering the points itself, just set in the configuration `itemRadius = 0`.
