### ISSUE TITLE
How to remove data text

### ISSUE THREAD

**Issue by coolcorey** [datavisyn/chartjs-chart-box-and-violin-plot#103]
How do I get rid of the data text displaying in the middle of the boxplot? I assume this is controlled by some chart option. I don't really know what it would be called, so I'm not sure what to refer to it as. Thanks.

<img width="846" alt="Screen Shot 2021-02-15 at 11 05 26 AM" src="https://user-images.githubusercontent.com/6085979/107976068-99b0df00-6f7e-11eb-90d3-7dcaaa1880c8.png">

**Comment by daniel-fidalgo-dive** [comment]
It's happening to me as well, did you manage to fix it?
