### ISSUE TITLE
chart-box-violin-plot not working with chart js 3

### ISSUE THREAD

**Issue by nishantbrevitaz** [datavisyn/chartjs-chart-box-and-violin-plot#107]
Now that new chart js v3.x has come up with no backward compatibility. Will this plugin work with this new version of chart js. If not when will you support ?

**Comment by nishantbrevitaz** [comment]
@sgratzl Can you help us here ?

**Comment by lilouch** [comment]
Any update for chartjs 3 ?

**Comment by dg-datavisyn** [comment]
Hi. Sorry for the delay. We are discussing this internally and I come back to you asap.

**Comment by petworthnick** [comment]
This plugin is awesome, but I'm trying to use the annotations plugin to indicator a marker on a box and violin chart. However, the annotation plugin only works with chartjs 3, so this update would be amazing!

**Comment by cerireyhan** [comment]
Is there any progress on this?

**Comment by ffaubert** [comment]
@dg-datavisyn Could you please give us some updated guidance on when you think you will be able to have a chart js 3.x version?

**Comment by dg-datavisyn** [comment]
Dear @ffaubert , this repos was moved back to Samuel and the latest version is available here: https://github.com/sgratzl/chartjs-chart-boxplot

This version will be depricated.
