### ISSUE TITLE
Boxplot/Violin type is not recognized

### ISSUE THREAD

**Issue by ohernandez018** [datavisyn/chartjs-chart-box-and-violin-plot#11]
Hi! I'm trying to paint a Boxplot chart but I got this error:

![error](https://user-images.githubusercontent.com/17454166/41157930-8356cfde-6b27-11e8-886b-a4f5699bcc9d.PNG)

I'm using an **Angular 5 project**. I have built `Chart.BoxPlot.js` previously and I have included in assets folder in my project. Also, I have included `chart.js` and `Chart.BoxPlot.js` files in `.angular-cli.json`:

`"scripts": [
        "../node_modules/chart.js/dist/Chart.bundle.js",
        "assets/Chart.BoxPlot.js"
      ]
`

Then, I have imported `chart.js` module in my `app.component.ts`:

`import * as Chart from 'chart.js';`

But the error appears all the time when I try to build a chart with `type: 'boxplot'` or `type: 'violin'`.

I'm a bit new with Angular 5 and I **really need help** to know how to make this works in an Angular project. A simple example would be so helpful.

Sorry if I explained myself wrong... and **thank you so much!!!**

**Comment by sgratzl** [comment]
take a look at: https://gist.github.com/sgratzl/61cf2fc0fac55434ff90c2a373108eae

I assume you are just missing the following line 
```
import 'chartjs-chart-box-and-violin-plot';
```

**Comment by ohernandez018** [comment]
@sgratzl Thank you so much! 👍
