### ISSUE TITLE
Example code pen doesn't show as expected

### ISSUE THREAD

**Issue by hoai-nguyen** [datavisyn/chartjs-chart-box-and-violin-plot#113]
- Please double check example code pen from https://github.com/datavisyn/chartjs-chart-box-and-violin-plot.
- This is pen's link: https://codepen.io/sgratzl/pen/QxoLoY.
- Please see below images for more details.

- Code pen doesn't show as expected: 
![image](https://user-images.githubusercontent.com/17783466/124694287-ec823780-df1b-11eb-948c-e12c9c35862e.png)

![image](https://user-images.githubusercontent.com/17783466/124685833-00726d00-df0d-11eb-9bb0-718d8b1e626d.png)

**Comment by hoai-nguyen** [comment]
![image](https://user-images.githubusercontent.com/17783466/124694829-fce6e200-df1c-11eb-895a-b3726ec7f075.png)

**Comment by Djones4822** [comment]
Can confirm that it is a source package issue. Installing via npm and importing yields the desired styling
