### ISSUE TITLE
Reduce range of displayed outliers / do not display outliers

### ISSUE THREAD

**Issue by MBlistein** [datavisyn/chartjs-chart-box-and-violin-plot#13]
Hi,

first of all thanks a lot for this plug-in, it works great!
I have one feature request though: would it be possible to not display outliers / reduce the range of displayed outliers? Otherwise, if there are outliers far away, it can make the plot a lot less readable (see attached). What I am most interested in are the median calculated quartiles; I am happy to chop off the fourth quartile at a certain point, knowing that there are outliers above. So if I could somehow set a flag to suppress outliers, that would be perfect.

Thanks!

![screenshot from 2018-07-13 08-50-06](https://user-images.githubusercontent.com/35335955/42679331-d8bc1220-8681-11e8-95ed-42582ad70143.png)

**Comment by sgratzl** [comment]
have you tried to set the `yScale` maximal value?

as in 

https://codepen.io/sgratzl/pen/ejpNoY?editors=0010

```js
window.myBar = new Chart(ctx, {
    type: 'boxplot',
    data: boxplotData,
    options: {
      responsive: true, 
      scales: {
            yAxes: [{
                ticks: {
                    max: 160
                }
            }]
        }
    }
  });
```

**Comment by MBlistein** [comment]
Very nice, thanks, will try and report back!

**Comment by HamsalekhaHR** [comment]
How to display Outliers values on Hover of outlier points... Please suggest

**Comment by sgratzl** [comment]
> How to display Outliers values on Hover of outlier points... Please suggest

please open a separate issue for that, thx

**Comment by mathijsfr** [comment]
Is there a sample of how to remove the outliers?
