### ISSUE TITLE
other chartjs chart not drawing on same page

### ISSUE THREAD

**Issue by primarycare** [datavisyn/chartjs-chart-box-and-violin-plot#17]
i am using your script to draw a boxplot. on same same page, i am also using the original chart.js to draw a doughnut and line chart.

when both chart.min.js and your chart.bundle.js where loaded in the html page, only your boxplot chart are drawn but not the chart.js ones . is there potentially a conflict between those two.

i tried drawn other chartsbusing your chart.bundle.js but neither doughnut or line chat appear? 

perhaps some mistake in my implementation?

**Comment by primarycare** [comment]
unfortunately, when using the chart.bundle.js, the same scriot that used to load chart.min.js were not able to draw on the canvas. 

anyway, thank you for enlighting me on this. I shall test editing the script in order to use chart.bundle.js. 

pardon me if my question are unfounded since it may not be related to ur boxplot script. And big thanks for sharing the boxplot script. it is very useful for my project to represent the data i wanted to showcase.

will report back if there were no further issue. but for now, i will keep this open until further testing? thanks

**Comment by primarycare** [comment]
btw, does your script require a specific version of chart.bundle.js?

**Comment by sgratzl** [comment]
> btw, does your script require a specific version of chart.bundle.js?

we tested this plugin with Chart.js 2.7.2 see https://github.com/datavisyn/chartjs-chart-box-and-violin-plot/blob/master/package.json#L17 but may work with older versions, too

re multiple charts: https://codepen.io/sgratzl/pen/PBmgKZ

**Comment by primarycare** [comment]
okay, i think this means this issue is resolve since u were able to draw the doughnut chart in your codepen example. thank a lot for sparing time 👍
