### ISSUE TITLE
missing build file in the release

### ISSUE THREAD

**Issue by truelife2** [datavisyn/chartjs-chart-box-and-violin-plot#24]
hi,there seems to be missing build files in the release zip file?

**Comment by sgratzl** [comment]
for what do you need the build files when installing the package via npm?

**Comment by truelife2** [comment]
sorry,i copy the js file to my core project's specified directory,and set to embedded resource;
than others project just need include the core project's dll, then teamplate auto load required js file
,not use an general solution

i see 1.0.0 has the build files,but newest seem without the build files

**Comment by truelife2** [comment]
ok,thx you very much,i will download from there

and thx your plugin, this help me very much
