### ISSUE TITLE
Uncaught Error: "boxplot" is not a chart type - Angularjs Issue

### ISSUE THREAD

**Issue by rehanhanar7** [datavisyn/chartjs-chart-box-and-violin-plot#28]
Uncaught Error: "boxplot" is not a chart type - Angularjs Issue

I am trying to use this chart on my angularjs project. I am getting this issue. Any idea ??

**Comment by sgratzl** [comment]
I had no problem when importing it, see https://codesandbox.io/s/9xpn7lxvp

**Comment by rehanhanar7** [comment]
Hi thanks for ur reply... the issue is in Angularjs import.. not angular 2...

**Comment by sgratzl** [comment]
I see. Tested it with https://github.com/sgratzl/angularjs-chartjs-boxplot and I get

![image](https://user-images.githubusercontent.com/4129778/52411257-6c9ddc00-2adb-11e9-9ef7-5ebfcaff699f.png)

**Comment by rehanhanar7** [comment]
Thanks Man will check into it !!
