### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by IsmailM** [datavisyn/chartjs-chart-box-and-violin-plot#29]
Hey guys,

I'm getting the following error in IE11:

```
Object doesn't support property or method 'assign'
```

The [main ChartJS branch support IE11](https://www.chartjs.org/docs/latest/developers/?h=internet%20Explorer%2011) so would be nice if this could also support IE11...

**Comment by sgratzl** [comment]
can you try v1.3.0?
