### ISSUE TITLE
BoxPlot.update() not working properly

### ISSUE THREAD

**Issue by Krockema** [datavisyn/chartjs-chart-box-and-violin-plot#31]
hy, 
first of all, great work!
The initial Drawing Looks good but,I run into one Problem, the BoxPot wont refresh after adding new values to it and Calling the ChartJs myChart.update() function. It just leaves a blank Chart without a boxplot (and not throwing any error either) 

any ideas, what i can do? 

Kind Regards.

**Comment by sgratzl** [comment]
can you provide an example e.g. by forking the codepen mentioned in the README?

**Comment by Krockema** [comment]
Hi, 

i was able to reproduce the failure it seem to apper when you push data into the Array
if you replace the Array it all goes fine. (see first update brakes the Chart (after 2 sek), second is working (after 4 sek)

https://codepen.io/anon/pen/XOvMbj?editors=0010

**Comment by sgratzl** [comment]
you mean like adding datasets or adding values to the array of which a boxplot is drawn?. In the latter case you try to not push to the same array instance but create a new one, as in 

https://codepen.io/sgratzl/pen/JxQVaZ?editors=0010

**Comment by sgratzl** [comment]
the issue is to avoid computing the stats over and over again which costs time, the computed values are stored in a attribute of the array called `___stats`. So far there is no check whether the data changes within the instance which would require to create some verification code which essentially would be as fast as computing the stats like all the time.

**Comment by Krockema** [comment]
Hi, 

that makes sense, but anyone who is pushing new data into that array should be aware of the recalculation. Is there a way to push just the precalculated quartiles into the chart? and append or add points just for outliers ? It would be more easy for me because i have thos values already calculated.

**Comment by sgratzl** [comment]
you're welcome

**Comment by sgratzl** [comment]
I added a note in https://github.com/datavisyn/chartjs-chart-box-and-violin-plot/commit/413a02538dbee013783ab65fb39a9bf6acf5cbb9
