### ISSUE TITLE
Question about how to use interface

### ISSUE THREAD

**Issue by Suguru-Tokuda** [datavisyn/chartjs-chart-box-and-violin-plot#35]
I'm trying to use an interface for box plot. I can't find any example for this. I created an array of objects which has the same attributes like q1 and q3 but it didn't draw the chart. Is there a sample that uses an interface?

```
interface IBoxPlotItem extends IBaseItem {
  q1: number;
  q3: number;
  whiskerMin?: number;
  whiskerMax?: number;
  /**
   * list of box plot outlier values
   */
  outliers?: number[];
}
```

**Comment by sgratzl** [comment]
take a look at https://codepen.io/sgratzl/pen/dreYEG

**Comment by Suguru-Tokuda** [comment]
Thanks!
