### ISSUE TITLE
Defining data structure with items

### ISSUE THREAD

**Issue by kbleabres** [datavisyn/chartjs-chart-box-and-violin-plot#41]
I'm trying to generate a boxplot chart with defined `min`, `q1`, `median`, `q3`, and `max` values, but I also want to show the jittered datapoints.

This is currently how I do it. using (technically) same data (array `[1, 2, 3, 4, 5]`)
https://codepen.io/anon/pen/MRGavN
The problem is, the datapoints aren't showing even if I add the items. They show up if I use `outliers` instead but they aren't jittered which is what I want.

**Comment by sgratzl** [comment]
thx for reporting, see #45 for a PR fixing this issue
