### ISSUE TITLE
Draw the chart without providing millions of data points

### ISSUE THREAD

**Issue by zHaytam** [datavisyn/chartjs-chart-box-and-violin-plot#43]
Hello,

As I understood from the examples, this addon needs the full list of points in order to draw the chart.
What if our dataset is huge and we already have Q1, Q2, Q3, mean and outliers and we want to draw the chart directly from these information?

Thank you!

**Comment by sgratzl** [comment]
Hi,
no you can also provide the boxplot data directly as an data object, having the following properties as pointed out in the README:

```ts
interface IBoxPlotItem {
  min: number;
  q1: number;
  median: number;
  q3: number;
  max: number;

  whiskerMin?: number;
  whiskerMax?: number;
  outliers?: number[];
}
```

**Comment by zHaytam** [comment]
Hey, yeah I figured it out after reading the source code.
Thank you!
