### ISSUE TITLE
Error: "boxplot" is not a chart type in VUE

### ISSUE THREAD

**Issue by jadsonjs** [datavisyn/chartjs-chart-box-and-violin-plot#47]
I am trying to use boxplot chart in my **Vue.js** project

I used the exact code of https://codesandbox.io/s/vy8r1x5ow5.  as a model.

I have install the the following plugins:
``
npm install --save chart.js vue-chartjs chartjs-chart-box-and-violin-plot
``

It install these versions:

> "chart.js": "^2.8.0",
> "chartjs-chart-box-and-violin-plot": "^2.1.0",
> "vue": "^2.6.10",
> "vue-chartjs": "^3.4.2",

I am using vue-cli 3.5.0 default project.

First, I got the same error of issue:  https://github.com/datavisyn/chartjs-chart-box-and-violin-plot/issues/32.

So, I delete the node_modules/chartjs-chart-box-and-violin-plot/build/Chart.BoxPlot.mjs file.

After that, I got the error:

> Invalid prop: type check failed for prop "chartData". Expected Object, got Null 

then, I change the time when the fillData() method is called from the mounted() to the beforeMount() method.:

``
beforeMount() {
     this.fillData();
},
``

It solve the problem of "Object, got Null", but I am now with another problem: 

**Error: ""boxplot" is not a chart type."
buildOrUpdateControllerswebpack-internal:///./node_modules/chart.js/dist/Chart.js:8670:12eachwebpack-internal:///./node_modules/chart.js/dist/Chart.js:1800:6buildOrUpdateControllerswebpack-internal:///./node_modules/chart.js/dist/Chart.js:8654:3updatewebpack-internal:///./node_modules/chart.js/dist/Chart.js:8725:24constructwebpack-internal:///./node_modules/chart.js/dist/Chart.js:8463:3Chartwebpack-internal:///./node_modules/chart.js/dist/Chart.js:8401:2renderChartwebpack-internal:///./node_modules/vue-chartjs/es/BaseCharts.js:74:29mountedwebpack-internal:///./src/components/studyone/BoxPlotChart.js:15:5invokeWithErrorHandlingwebpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1853:49callHookwebpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4207:7insertwebpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3136:7invokeInsertHookwebpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6330:9patchwebpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6549:5_updatewebpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3936:16updateComponentwebpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4054:7getwebpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4467:13runwebpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4542:17flushSchedulerQueuewebpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4298:5nextTickwebpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1979:9flushCallbackswebpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1905:5runwebpack-internal:///./node_modules/core-js/modules/es6.promise.js:75:22notifywebpack-internal:///./node_modules/core-js/modules/es6.promise.js:92:30flushwebpack-internal:///./node_modules/core-js/modules/_microtask.js:18:9 vue.runtime.esm.js:1888**

Someone have any ideas about how to resolve this?
Thank you

**Comment by sgratzl** [comment]
can you take a look at https://github.com/sgratzl/vue-chartjs-boxplot

based on the sandbox I created a standalone version. Instead of changing the dependency, I changed the `vue.config.js` to proper handle the `.mjs` files.

**Comment by jadsonjs** [comment]
Perfect !!!

I just added the `vue.config.js` file in my project root (same level of package.json) and restored the Chart.BoxPlot.mjs file.

Now it works worked perfectly like the example https://codesandbox.io/s/vy8r1x5ow5.

Thank you very much!
