### ISSUE TITLE
alternating white and grey behind group

### ISSUE THREAD

**Issue by andreassteffen** [datavisyn/chartjs-chart-box-and-violin-plot#5]
to better differentiate groups in boxplot

**Comment by sgratzl** [comment]
Actually the groups are managed by Chart.js itself. This plugin just renders the boxplot within

**Comment by sluger** [comment]
This should work for both vertical and horizontal plots, as well as for box and violin plots and generic chart types such as bars, lines, etc.

**Comment by andreassteffen** [comment]
great! Many thanks!!!

**Comment by sluger** [comment]
Hi @andreassteffen, I have now released this as a NPM package which supports barcharts, boxplots and violin plots. See https://www.npmjs.com/package/chartjs-plugin-barchart-background
