### ISSUE TITLE
Outlier Tooltip on Hover of Outlier Point 

### ISSUE THREAD

**Issue by HamsalekhaHR** [datavisyn/chartjs-chart-box-and-violin-plot#51]
How to display Outliers values on Hover of outlier points... Please suggest

**Comment by sgratzl** [comment]
it is not possible right now. For Chart.js the whole boxplot (box + outliers) is just one element that can be hovered. For now, only when the user hits the box a tooltip will be triggered.

**Comment by sgratzl** [comment]
I start developing a patch for it at https://github.com/datavisyn/chartjs-chart-box-and-violin-plot/pull/52

**Comment by HamsalekhaHR** [comment]
Thank you for considering the request... Will wait for updated version with outlier hover enabled...

**Comment by HamsalekhaHR** [comment]
Hello Mr.Samuel, when can I update chartjs-chart-box-and-violin-plot package so that hover outlier tooltip is displayed...

**Comment by sgratzl** [comment]
@lehnerchristian ping regarding PR

**Comment by lehnerchristian** [comment]
hi, @HamsalekhaHR and @sgratzl ! we'll try to merge this PR asap. I'll let you know, @HamsalekhaHR

**Comment by HamsalekhaHR** [comment]
Hello Sir, Can you please let me know so as to when new plugin with Outlier tooltip update will be available for use...

**Comment by sgratzl** [comment]
I don't know. In the meanwhile you can directly use the branch by installing:

```bash
npm i datavisyn/chartjs-chart-box-and-violin-plot#sgratzl/outliertooltip
```

**Comment by lehnerchristian** [comment]
I think this depends on the dependent issue and branch: https://github.com/datavisyn/chartjs-chart-box-and-violin-plot/issues/53#issuecomment-548417318

**Comment by lehnerchristian** [comment]
@HamsalekhaHR , the corresponding PRs are now merged into the develop branch

**Comment by HamsalekhaHR** [comment]
Outlier tooltip is enabled, Thank you
