### ISSUE TITLE
Whiskers being drawn within area of Q1-Q3

### ISSUE THREAD

**Issue by acochrane-nvx** [datavisyn/chartjs-chart-box-and-violin-plot#59]
With data with extreme outliers, I am finding a lot of times this chart style is drawing the whiskers above Q1 and below Q3. Is there a way to keep this from happening?
![image](https://user-images.githubusercontent.com/46050782/69083423-72d0c980-0a18-11ea-9be0-99ecd4b23c07.png)

**Comment by sgratzl** [comment]
it depends on how one computes the whiskers, can you try the latest develop branch, it also provides more options to specify how the whiskers should be computed. 

```bash
npm install github:datavisyn/chartjs-chart-box-and-violin-plot#develop
```

re options: 
https://github.com/datavisyn/chartjs-chart-box-and-violin-plot/tree/develop#scale-options or https://github.com/datavisyn/chartjs-chart-box-and-violin-plot/blob/develop/samples/fivenum.html as an example

**Comment by acochrane-nvx** [comment]
This is using the latest version (2.8.0?) and no tick options, just defaults. What sort of options should I be using to make sure the whiskers are always above and below the box?
