### ISSUE TITLE
Wrong boxplot graph

### ISSUE THREAD

**Issue by kstopia** [datavisyn/chartjs-chart-box-and-violin-plot#64]
So, I was using this data:
```
4.16666666666667,7.14285714285714,7.14285714285714,8.88888888888889,9.09090909090909,10,10,10,10.5263157894737,11.1111111111111,12.5,14.2857142857143,14.2857142857143,15.625,18.1818181818182,20,25,25,25,33.3333333333333,33.3333333333333,50,100,100,100,100
```
The tooltip is correct, but the graph is somewhat incorrect. 
This is my code: 
```js
function randomValues(count, min, max) {
  //const delta = max - min;
  //return Array.from({length: count}).map(() => Math.random() * delta + min);
  var dataSet = [];
  dataSet = [4.16666666666667, 7.14285714285714, 7.14285714285714, 8.88888888888889, 9.09090909090909, 10.000000, 10.000000, 10.000000, 10.5263157894737, 11.1111111111111, 12.5, 14.2857142857143, 14.2857142857143, 15.625, 18.1818181818182, 20.000000, 25.000000, 25.000000, 25.000000, 33.3333333333333, 33.3333333333333, 50.000000, 100.000000, 100.000000, 100.000000, 100.000000];
  return dataSet.sort();
}
//console.log(randomValues(100, 0, 100));
const boxplotData = {
  // define label tree
  labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
  datasets: [{
    label: 'Dataset 1',
    backgroundColor: 'rgba(255,0,0,0.5)',
    borderColor: 'red',
    borderWidth: 1,
    outlierColor: '#999999',
    padding: 10,
    itemRadius: 0,
    data: [
      randomValues(100, 0, 100),
      randomValues(100, 0, 20),
      randomValues(100, 20, 70),
      randomValues(100, 60, 100),
      randomValues(40, 50, 100),
      randomValues(100, 60, 120),
      randomValues(100, 80, 100)
    ]
  }, {
    label: 'Dataset 2',
    backgroundColor:  'rgba(0,0,255,0.5)',
    borderColor: 'blue',
    borderWidth: 1,
    outlierColor: '#999999',
    padding: 10,
    itemRadius: 0,
    data: [
      randomValues(100, 60, 100),
      randomValues(100, 0, 100),
      randomValues(100, 0, 20),
      randomValues(100, 20, 70),
      randomValues(40, 60, 120),
      randomValues(100, 20, 100),
      randomValues(100, 80, 100)
    ]
  }]
};
window.onload = () => {
  const ctx = document.getElementById("canvas").getContext("2d");
  window.myBar = new Chart(ctx, {
    type: 'boxplot',
    data: boxplotData,
    options: {
      responsive: true,
      legend: {
        position: 'top',
      },
      title: {
        display: true,
        text: 'Chart.js Box Plot Chart'
      }
    }
  });
};

```

![image](https://user-images.githubusercontent.com/58965823/70964661-35b33200-20bf-11ea-8e19-3d78c4cea158.png)

Could you please help me? Thanks before 💃

**Comment by sgratzl** [comment]
can you describe what type of image you were expecting?

**Comment by kstopia** [comment]
![image](https://user-images.githubusercontent.com/58965823/70968587-31d9dc80-20cc-11ea-8cdd-69a9cd9f2c03.png)

Like this one, where the "max" line is appeared until 100. While in the the screenshot before this one, the "max" line appeared only to 50

**Comment by sgratzl** [comment]
there is no max-line, the whiskers go to the +/- 1.5 * inter quartile range (IQR). If they should extend to the min/max data points you can change the `coef` option of the corresponding scale to `0`. see also the README for other options

**Comment by kstopia** [comment]
Ahh i see. I'm still new in this whole "boxplot" thing. So pardon for my "noob" question. Anyway, I have read the Readme, but I'm still confused. Let's say that I want to change the coef of the red boxplot in January section to 0. Where to put that "coef" option? 

Thanks for your help, really appreciate it.

**Comment by sgratzl** [comment]
take a look at 

https://codepen.io/sgratzl/pen/yLyVjjR?editors=0010

you can only change the option globally for the whole chart. Otherwise, it might create confusion when boxplots of the same chart have different meaning and interpretation

**Comment by kstopia** [comment]
Ahh, I see. Thanks a lot for your help! Hopefully this post can help another ppl who have the same problem as me. Once again, thanks 😄 👍
