### ISSUE TITLE
Means, Median Tooltip doesnt appear 

### ISSUE THREAD

**Issue by HamsalekhaHR** [datavisyn/chartjs-chart-box-and-violin-plot#65]
Median Tooltip doesnt appear when line is vertial... Please suggest..

![image](https://user-images.githubusercontent.com/55982503/71161003-9634a180-226e-11ea-88a1-1d6207339e37.png)

**Comment by sgratzl** [comment]
can you create an example on codepen? https://codepen.io/sgratzl/pen/QxoLoY is a basic setup

**Comment by HamsalekhaHR** [comment]
ok Sir... will do and share the link
