### ISSUE TITLE
Quantiles Methods not working

### ISSUE THREAD

**Issue by Rovel** [datavisyn/chartjs-chart-box-and-violin-plot#66]
Hi,

I'm trying to apply different quantile methods to match a report made in another lib used by Re-Dash but it seem as I change the quantiles the graph value does not change.
**Example Code:**
https://codepen.io/Rovel/pen/RwwdzbG

**Reference Issue:**
https://github.com/getredash/redash/issues/4428

**Comment by sgratzl** [comment]
1. you have to change the quantiles method in the "xAxes" since you have a horizontal box plot
2. even if you change it to e.g. `fivenum` in my test the results don't change even with the different method.

**Comment by Rovel** [comment]
@sgratzl  yes I tried this too, xAxes and try actually all available quantiles methods and nothing changes, not sure if is a thing in the horizontal Box, but with numpy and other command line libs the value change, so I must infer that is something in the horizontal box and quantiles methods in this lib, can you confirm that the quantiles methods are working in the horizontal box plot?
Thanks

**Comment by sgratzl** [comment]
can you give a dataset in which you can see different results and also the code (e.g python,...) how to compute the various formats? The different methods that are currently implemented show an effect especially on dataset with an even number of elements since they essentially have different methods to combine two values for q1, q3, median, ...

**Comment by Rovel** [comment]
Hi,

See if this is is enought info, 11 numbers, evaluationg only q3 but from here we can test the others too...

Here follows a dataset and a example running with **python 3.8.1** with the **numpy** lib:
- Dataset is the same I used in the [Codepen Reference:](https://codepen.io/Rovel/pen/RwwdzbG)
`x = [3.375, 3.75, 3.875, 3, 3, 3.5, 3.125, 3, 2.625, 3.375, 3]`
- Output:
![Screen Shot 2020-01-22 at 17 01 42](https://user-images.githubusercontent.com/2469500/72929687-18febf80-3d39-11ea-8e7f-92f809565ee4.png)
- Numpy Reference:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.percentile.html
- Output in text:
```
>>> import numpy as np
>>> x = [3.375, 3.75, 3.875, 3, 3, 3.5, 3.125, 3, 2.625, 3.375, 3]
>>> np.percentile(x, 75, interpolation='linear')
3.4375
>>> np.percentile(x, 75, interpolation='higher')
3.5
>>> np.percentile(x, 75, interpolation='lower')
3.375
>>> np.percentile(x, 75, interpolation='nearest')
3.5
>>> np.percentile(x, 75, interpolation='midpoint')
3.4375
```

**Comment by sgratzl** [comment]
I see, there seem to be numerous versions how to compute the value in case you have to interpolate it. 

So far this library implements two methods taken from R
 * type-7 method https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/quantile
 * the 'hinges' as used in https://www.rdocumentation.org/packages/grDevices/versions/3.6.2/topics/boxplot.stats.

The latter was added to be the same as when using the R `boxplot` function. 

However, I can take a look to also implement the other methods. A PR is also welcome

**Comment by Rovel** [comment]
sure I will try to help with a PR or something, but since JS is not my strong suit it will probably need a good review 😃
