### ISSUE TITLE
Set box max width

### ISSUE THREAD

**Issue by christiaan-lombard** [datavisyn/chartjs-chart-box-and-violin-plot#76]
Is there a way to set the max width of a box-plot rectangle. If my dataset only contains one or two items I not want it to stretch as below:

![image](https://user-images.githubusercontent.com/6524763/76508464-15dda100-6457-11ea-845b-9512de988092.png)

I saw in another issue that a box plot uses the Bar Controller but maxBarThickness is not working.

**Comment by sgratzl** [comment]
have you tried: https://codepen.io/sgratzl/pen/qBdxeYj?editors=1010

**Comment by sgratzl** [comment]
does it work? if so please close this issue

**Comment by christiaan-lombard** [comment]
Ahh, I see the `maxBarThickness`  is a option of the *xAxis*, not the Dataset as the documentation suggests (https://www.chartjs.org/docs/latest/charts/bar.html).

Thanks
