### ISSUE TITLE
how do you implement line for average value in Chart.js Box and Violin Plot

### ISSUE THREAD

**Issue by sopanshelar** [datavisyn/chartjs-chart-box-and-violin-plot#86]
I have to integrate a line to show the average value in the box plot chart uing angular 8 but could not get the solution to integrate it. below is the screenshot of the output.
![image](https://user-images.githubusercontent.com/54016616/92373747-6db24780-f11c-11ea-97ec-cdf0e0066ba8.png)

**Comment by klickparkdominik** [comment]
You could use the segment option which will draw a (blue) line on a specific value / position. For example the calculated average.

Check out this example: https://github.com/datavisyn/chartjs-chart-box-and-violin-plot/blob/master/samples/vertical_segment.html

![sample](https://user-images.githubusercontent.com/46604496/112622596-8cafc700-8e2b-11eb-9707-6cf9057d6d37.jpg)

**Please note:**
Unfortunately I had to install the package via the following command, to get things running:
`npm install --save datavisyn/chartjs-chart-box-and-violin-plot#v2.4.0`

Although version 2.4.0 was also installed with the following command, a few lines of code are missing in the source code that actually draw the segment:
`npm install --save chartjs-chart-box-and-violin-plot`

Maybe something went wrong during the publishing process to npm?
