### ISSUE TITLE
How do I add segment line for each box plot 

### ISSUE THREAD

**Issue by sopanshelar** [datavisyn/chartjs-chart-box-and-violin-plot#90]
I have created a one sample using chartjs-chart-box-and-violin-plot in angular 8, now I have to add a segment line for each box plot .I am not getting any solution to add an line into it.

![image](https://user-images.githubusercontent.com/54016616/92721760-38a82e00-f384-11ea-9d82-b8d338108a46.png)
Above screenshot is I have to create and below is the sample that I have created.
![image](https://user-images.githubusercontent.com/54016616/92721933-773de880-f384-11ea-9e80-58a785551ce3.png)
How do I add segment line into it ?

**Comment by tscans** [comment]
Did you solve this? This would be very helpful.

**Comment by tscans** [comment]
@sopanshelar This has been added.

https://github.com/datavisyn/chartjs-chart-box-and-violin-plot/pull/95

**Comment by mschwerhoff** [comment]
Has the segment feature already been released?

I've downloaded [vertical_segment.html](https://github.com/tscans/chartjs-chart-box-and-violin-plot/blob/master/samples/vertical_segment.html) and tried it with

```html
<script src="https://unpkg.com/chart.js@2.9.4/dist/Chart.bundle.min.js"></script>
<script src="https://unpkg.com/chartjs-chart-box-and-violin-plot@2.3.0/build/Chart.BoxPlot.min.js"></script>
```

and 

```html
<script src="https://unpkg.com/chart.js@3.0.0-beta.10/dist/chart.min.js"></script>
<script src="https://unpkg.com/@sgratzl/chartjs-chart-boxplot@3.0.0-beta.9/build/index.umd.min.js"></script>
```

but in both cases, the box plots only show a green median bar, but not the expected blue segment bar.

Any idea what the problem could be?

**Comment by tscans** [comment]
@mschwerhoff The segment is in master. So you can try and hit that directly. Otherwise you could try and convince the owner of the repo to release the latest version.

**Comment by tscans** [comment]
@dg-datavisyn Is there any way we could release that? I would certainly benefit from it as well.
