### ISSUE TITLE
Boxplot Item Border Color

### ISSUE THREAD

**Issue by beyond7** [datavisyn/chartjs-chart-box-and-violin-plot#93]
Boxplot `itemBorderColor` is not set correctly. 

![Screen Shot 2020-10-13 at 11 58 47 AM](https://user-images.githubusercontent.com/52490076/95852327-7ca79d80-0d4b-11eb-98af-2d38186a1a1f.png)

Maybe this is because it's setting to `strokeStle`?

**Comment by afraser** [comment]
Yep, noticed the same issue. Should be `strokeStyle`.

**Comment by afraser** [comment]
FWIW: This is a real problem applications with a dark styling since black points aren't really visible against a dark background.

**Comment by BenDavisson** [comment]
@afraser @beyond7   I ran into the same issue.  I submitted a pull request with the typo fixed.
