### ISSUE TITLE
Boxplot generate not correct chart view

### ISSUE THREAD

**Issue by mrandreev** [datavisyn/chartjs-chart-box-and-violin-plot#94]
Hey there, 

I have found strange behavior of chart with the following case:
```
data: [1,1,4,4,4,4,4,4]
type: horizontalBoxplot
```

The result of calculations looks ok, but the actual chart view looks strange. 
Also hover doesn't work properly (it works only over x-axis '4')

**Code example:**
https://codepen.io/mrandreev/pen/VwjpzvB

**Actual result**
![image](https://user-images.githubusercontent.com/19778013/97163480-60fbb880-1789-11eb-97ff-6c2f4aa9b8df.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/19778013/97159531-b46b0800-1783-11eb-911e-34df63cffcbc.png)

**Comment by aamir0** [comment]
I found the same thing even with just 4 data points (18, 18, 20, 39). It looks like if the max value (excluding outlier) is less than Q3, the whisker is drawn inside the box.
https://codepen.io/aamir0-the-decoder/pen/RwRBYOq

![image](https://user-images.githubusercontent.com/3621093/98270850-4a114f00-1f5d-11eb-9f18-dfa63ddfbed8.png)
